### ISSUE TITLE
pycsdr error:

### ISSUE THREAD

**Issue by KO4BJV** [jketterl/pycsdr#5]
Hi i'm no expert here. I have openwebrx runing on Armbian bookworm X86. Openwebrx works great, how ever I get error trying to install pycsdr.

/usr/bin/ld: cannot find -lcsdr: No such file or directory
collect2: error: ld returned 1 exit status
error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

**Comment by jketterl** [comment]
If OpenWebRX is already running for you, you should already have an installation of `pycsdr`, and there should be no need to perform another installation. I'd recommend reviewing your course of action since you may be about to upset a working setup beyond repair.

If you still want to run the installation for whatever reason, you'll need to make sure that the required dependencies are available. In this case, you seem to be missing the development files for `csdr`. If you're installing from packages, the development files are available in a separate package, `lisbcsdr-dev`.

If you have further questions, please use the OpenWebRX mailing list for support.
